const PDFDocument = require('pdfkit');

const formatIDR = (n) =>
  'Rp ' + Number(n || 0).toLocaleString('id-ID', { maximumFractionDigits: 0 });

const formatDate = (d) => (d ? new Date(d).toLocaleDateString('id-ID', { day: '2-digit', month: 'short', year: 'numeric' }) : '-');

const renderInvoicePdf = (invoice, { clinicName = 'DentalCare Clinic', clinicAddress = '' } = {}) => {
  const doc = new PDFDocument({ size: 'A4', margin: 48 });

  // Header
  doc.fontSize(20).font('Helvetica-Bold').text(clinicName, { align: 'left' });
  if (clinicAddress) doc.fontSize(9).font('Helvetica').fillColor('#555').text(clinicAddress);
  doc.fillColor('#000');

  doc.moveUp(2);
  doc.fontSize(20).font('Helvetica-Bold').text('INVOICE', { align: 'right' });
  doc.fontSize(10).font('Helvetica').text(invoice.invoiceNumber, { align: 'right' });
  doc.text(formatDate(invoice.createdAt), { align: 'right' });

  doc.moveDown(2);
  doc.moveTo(48, doc.y).lineTo(547, doc.y).strokeColor('#e5e7eb').stroke();
  doc.moveDown(1);

  // Bill to
  const patient = invoice.patientId || {};
  const dentist = invoice.dentistId || {};
  const appt = invoice.appointmentId || {};

  doc.fontSize(10).font('Helvetica-Bold').text('Bill To:');
  doc.font('Helvetica').text(patient.name || '-');
  if (patient.email) doc.text(patient.email);
  if (patient.phone) doc.text(patient.phone);
  if (patient.address) doc.text(patient.address);

  doc.moveUp(4);
  doc.font('Helvetica-Bold').text('Treatment:', 300);
  doc.font('Helvetica').text(`Dentist: ${dentist.name || '-'}`, 300);
  if (appt.appointmentDate) {
    doc.text(`Date: ${formatDate(appt.appointmentDate)} ${appt.appointmentTime || ''}`, 300);
  }
  if (appt.serviceId && appt.serviceId.title) {
    doc.text(`Service: ${appt.serviceId.title}`, 300);
  }

  doc.moveDown(2);

  // Items table
  const tableTop = doc.y + 10;
  doc.font('Helvetica-Bold').fontSize(10);
  doc.text('Description', 48, tableTop);
  doc.text('Qty', 320, tableTop, { width: 40, align: 'right' });
  doc.text('Unit Price', 370, tableTop, { width: 80, align: 'right' });
  doc.text('Amount', 460, tableTop, { width: 80, align: 'right' });
  doc.moveTo(48, tableTop + 15).lineTo(547, tableTop + 15).strokeColor('#e5e7eb').stroke();

  doc.font('Helvetica').fontSize(10);
  let y = tableTop + 22;
  (invoice.items || []).forEach((it) => {
    doc.text(it.description, 48, y, { width: 260 });
    doc.text(String(it.quantity), 320, y, { width: 40, align: 'right' });
    doc.text(formatIDR(it.unitPrice), 370, y, { width: 80, align: 'right' });
    doc.text(formatIDR(it.amount), 460, y, { width: 80, align: 'right' });
    y += 22;
  });

  doc.moveTo(48, y).lineTo(547, y).strokeColor('#e5e7eb').stroke();
  y += 10;

  const rightCol = 370;
  const drawRow = (label, value, bold = false) => {
    doc.font(bold ? 'Helvetica-Bold' : 'Helvetica').fontSize(10);
    doc.text(label, rightCol, y, { width: 80, align: 'right' });
    doc.text(value, 460, y, { width: 80, align: 'right' });
    y += 18;
  };

  drawRow('Subtotal', formatIDR(invoice.subtotal));
  if (invoice.discount) drawRow('Discount', `- ${formatIDR(invoice.discount)}`);
  if (invoice.tax) drawRow(`Tax (${invoice.taxRate}%)`, formatIDR(invoice.tax));
  drawRow('TOTAL', formatIDR(invoice.total), true);
  if (invoice.downPaymentApplied) {
    drawRow('DP Applied', formatIDR(invoice.downPaymentApplied));
  }
  if (invoice.amountPaid) drawRow('Paid', formatIDR(invoice.amountPaid));
  if (invoice.amountPaid && invoice.amountPaid < invoice.total) {
    drawRow('Balance', formatIDR(invoice.total - invoice.amountPaid), true);
  }

  // Status
  doc.moveDown(2);
  doc.font('Helvetica-Bold').fontSize(11);
  const statusLabel = invoice.paymentStatus.toUpperCase();
  const statusColor = invoice.paymentStatus === 'paid' ? '#16a34a' : invoice.paymentStatus === 'partial' ? '#ca8a04' : '#dc2626';
  doc.fillColor(statusColor).text(`Status: ${statusLabel}`, 48, y + 10);
  if (invoice.paidAt) doc.fillColor('#555').font('Helvetica').fontSize(9).text(`Paid at: ${formatDate(invoice.paidAt)}`, 48);
  if (invoice.paymentMethod) doc.text(`Method: ${invoice.paymentMethod}`, 48);

  doc.fillColor('#000');

  // Footer
  doc.fontSize(8).font('Helvetica').fillColor('#888').text(
    `Generated by DentalCare on ${formatDate(new Date())}`,
    48,
    780,
    { align: 'center', width: 499 }
  );

  doc.end();
  return doc;
};

module.exports = { renderInvoicePdf };
